export const FIND_MATCH = "FIND_MATCH";
export const FIND_MATCH_SUCCEEDED = "FIND_MATCH_SUCCEEDED";

export const ADD_MATCH = "ADD_MATCH";
export const REMOVE_MATCH = "REMOVE_MATCH";

export const POST_DATA = "POST_DATA";
export const POST_DATA_SUCCEEDED = "POST_DATA_SUCCEEDED";
